apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Pod
      name: kube-apiserver
    path: patch.yaml
